config/routes.rb
Balder::Application.routes.draw do
  resource :account, :controller => :users
  match "login", :to => "user_sessions#new", :as => :login
  match "authenticate", :to => "user_sessions#create", :as => :authenticate
  match "logout", :to => "user_sessions#destroy", :as => :logout

  resources :photos do
    collection do
      get :untouched
      post :edit_multiple
      put :update_multiple
      get :upload
      get :scan
    end
  end
  resources :albums do
    collection do
      get :untouched
    end
    resources :tags do
      resources :photos do
        collection do
          get :untouched
          get :upload
          get :edit_multiple
        end
      end
    end
    resources :photos do
      collection do
        get :untouched
        get :upload
        get :edit_multiple
      end
    end
  end
  resources :collections do
    resources :albums do
      resources :photos do
        collection do
          get :untouched
          get :upload
          get :edit_multiple
        end
      end
    end
  end
  
  resources :tags, :shallow => true do
    resources :photos
    resources :albums
  end
  
  resources :users, :controller => "admin/users"
  
  root :to => "collections#index"

end

app/models/collection.rb
class Collection < ActiveRecord::Base
  has_many :collection_albums
  has_many :albums, :through => :collection_albums
  attr_accessor :album_list

  validates :title, :presence => true

  def to_param
     "#{id}-#{title.parameterize}"
  end
  
  def album_list=(albums)
    self.albums = Album.find(albums.map{|album|album[0]})
  end

end

app/controllers/collections_controller.rb
# encoding: UTF-8

class CollectionsController < ApplicationController
  before_filter :check_public_access
  before_filter :require_role_admin, :only => [:new, :create, :edit, :update, :destroy]

  def index
    @collections = Collection.find(:all, :order => 'title')
    respond_to do |format|
      format.html
      format.json  { render :json => @collections }
      format.xml  { render :xml => @collections }
    end
  end
  
  def show
    @collection = Collection.find( params[:id] )
    @albums = @collection.albums.find(:all, :order => 'title')
    respond_to do |format|
      format.html
      format.json  { render :json => @collection }
      format.xml  { render :xml => @collection }
      format.pdf { render :pdf => @collection.title }
    end
  end
    
  def new
    @collection = Collection.new
  end

  def create
    @collection = Collection.new(params[:collection])
    if @collection.save
      flash[:notice] = "Zusammenstellung erstellt! Füge nun ein neues Album hinzu"
      redirect_to new_collection_album_path(@collection)
    else
      render :action => :new
    end
  end
  
  def edit
    @collection = Collection.find( params[:id])
  end

  def update
    @collection = Collection.find( params[:id])
    if @collection.update_attributes(params[:collection])
      flash[:notice] = "Zusammenstellung bearbeitet"
      redirect_to @collection
    else
      render :action => :edit
    end
  end
  
  def destroy
    @collection = Collection.find( params[:id])
    if @collection.destroy
      redirect_to collections_path
    else
      redirect_to @collection
    end
  end
  
end

app/views/collections/_form.html.erb
<%= form.label :title, {:class => 'big'} %><br />
<%= form.text_field :title, {:class => 'big'} %><br />

<%= form.label :description %><br />
<%= form.text_area :description %><br />

<% unless @collection.albums.empty? %>
<%= form.label :albums %><br />
<div id="collection_albums">
<% for album in @collection.albums %>
<%= form.fields_for :album_list do |album_fields| %>
<span>
<%= image_tag "delete-24x24.png", :class => "delete", :alt => "Delete" -%>

<% if album.photos.empty? %>
	<%= album.title %>
<% else %>
<%= image_tag album.photos.first.file.album.url, :alt => album.title %>
<% end %>
<%= album_fields.hidden_field album.id %>
</span>
<% end %>
<% end %>
</div>

<p class="clear">
<%
grouped_options = [
	['Verfügbare Alben',[['Wähle ein Album','']]],
	['Nicht in Benutzung', Album.unused.map{|album|[album.title, album.id]} ],
	['In Benutzung', Album.used.map{|album|[album.title, album.id]} ]
]
grouped_options_for_select(grouped_options)
%>
<%= select_tag 'available_albums', grouped_options_for_select(grouped_options) %>
</p>

<% end %>

app/views/collections/edit.html.erb
<h1>Zusammenstellung Bearbeiten</h1>
 
<%= form_for @collection do |f| %>
  <%= f.error_messages %>
  <%= render :partial => "form", :object => f %>
  <%= f.submit "Speichern" %>
<% end %>

<%= content_for :action_links do %>
<%= link_to("Diese Zusammenstellung löschnen", { :action => "destroy", :id => @collection },
  :confirm => "Bist du sicher das du diese Zusammenstellung löschen möchtest?",
  :method => :delete) %>
<% end %>

app/views/collections/index.html.erb
<div id="multipleimages">
<% for collection in @collections %>
	<div class="thumb">
		<h3><%= link_to collection.title, collection %></h3>
		<%= link_to (image_tag collection.albums.find(:first).photos.first.file.collection.url ), collection_path(collection) unless collection.albums.empty? || collection.albums.find(:first).photos.empty? %>
	</div>
<% end %>
</div>

<%= content_for :action_links do %>
<% if has_role?("admin") %>
<%= link_to "Neue Zusammenstellung", new_collection_path %>
<% end %>
<% end %>

app/views/collections/new.html.erb
<h1>Neue Zusammenstellung</h1>
 
<%= form_for @collection do |f| %>
  <%= f.error_messages %>
  <%= render :partial => "form", :object => f %>
  <%= f.submit "Erstellen" %>
<% end %>

app/views/collections/show.html.erb
<h2><%= h @collection.title %></h2>
<p><%= h @collection.description %></p>

<% for album in @albums %>
<div class="row">
  <div class="title">
	<%= render :partial => "photos/thumb", :locals => {:photo => album.photos.first } unless album.photos.empty? %>
	<p><%= link_to album.title, collection_album_path(@collection, album) %></p>
  </div>
  <div class="image">
	<%= render :partial => "photos/thumb", :collection => album.photos.find(:all, :limit => 5, :offset => 1), :as => :photo %>
  </div>
</div>
<% end %>

<%= content_for :action_links do %>
<% if has_role?("admin") %>
<%= link_to "PDF", collection_path(@collection, :format => 'pdf') %> |&nbsp;
<%= link_to "Zusammenstellung Bearbeiten", edit_collection_path(@collection) %> | 
<%= link_to "Neues Album", new_collection_album_path(@collection) %>
<% end %>
<% end %>

app/views/collections/show.pdf.erb
<h2><%= h @collection.title %></h2>
<p><%= h @collection.description %></p>

<% for album in @collection.albums %>
<h3><%= album.title %></h3>
<p><%= render :partial => album.photos %></p>

<% end %>