config/routes.rb
Balder::Application.routes.draw do
  resource :account, :controller => :users
  match "login", :to => "user_sessions#new", :as => :login
  match "authenticate", :to => "user_sessions#create", :as => :authenticate
  match "logout", :to => "user_sessions#destroy", :as => :logout

  resources :photos do
    collection do
      get :untouched
      post :edit_multiple
      put :update_multiple
      get :upload
      get :scan
    end
  end
  resources :albums do
    collection do
      get :untouched
    end
    resources :tags do
      resources :photos do
        collection do
          get :untouched
          get :upload
          get :edit_multiple
        end
      end
    end
    resources :photos do
      collection do
        get :untouched
        get :upload
        get :edit_multiple
      end
    end
  end
  resources :collections do
    resources :albums do
      resources :photos do
        collection do
          get :untouched
          get :upload
          get :edit_multiple
        end
      end
    end
  end
  
  resources :tags, :shallow => true do
    resources :photos
    resources :albums
  end
  
  resources :users, :controller => "admin/users"
  
  root :to => "collections#index"

end

app/models/album.rb
class Album < ActiveRecord::Base
  has_many :photos, :dependent => :destroy
  has_many :collection_albums
  has_many :collections, :through => :collection_albums

  validates :path, :presence => true, :uniqueness => true #, :message => "Album already exsists on disc"
  validates :title, :presence => true #, :message => "can't be blank"
  
  before_validation :ensure_path, :set_title
  after_create :create_folders
  after_destroy :destroy_folders

  attr_accessor :tags
  #attr_protected :path
  
  scope :untouched, where("albums.id IN ( SELECT DISTINCT photos.album_id FROM photos WHERE photos.description IS NULL AND photos.id NOT IN ( SELECT photo_id FROM photo_tags) )").order('title')
  scope :unused, where("albums.id NOT IN (SELECT album_id FROM collection_albums)")
  scope :used, where("albums.id IN (SELECT album_id FROM collection_albums)")

  def to_param
    "#{id}-#{title.parameterize}"
  end
  
  def ensure_path
    self.path = self.title.parameterize unless self.path
  end
  
  def set_title
    self.title = File.basename(self.path).titleize unless self.title || !self.path
  end
  
  def tags
    # should maybe cache this to database?
    # should maybe return array instead?
    
    tags = Array.new
    self.photos.map{ |photo|
        if photo.tags.empty?
          # photo has no tags => no unversial tags for this album
          return
        else
          photo.tags
        end
    }.each_with_index{ |photo_tags,i|
        # returns tag collection for each photo
        if i == 0
          tags = photo_tags
        else
          # combine arrays if they have identical tags.
          # Will remove tags that are only tagged to one photo
          #tags = tags & photo_tags
          tags = tags & photo_tags
        end
    }
    return tags
  end
  
  def tags=(tags)
    tags = tags.split(" ").sort
    current_tags = ( self.tags.nil? ? [] : self.tags.map{|tag|tag.title} )
    return if tags == self.tags
    
    # find tags that should be removed from this album - thus remove from all photos in album
    # i.e. tags listed in self.tag_list but no in parameter tags
    #current_tags.map {|tag|tag if !tags.include?(tag) }.compact
    (current_tags - tags).each { |tag|
      self.photos.each {|photo|
        photo.untag( tag )
      }
    }

    # add universial tags to all photos in album
    (tags - current_tags).each do |tag|
      self.photos.each { |photo|
        photo.tag( tag )
      }
    end
  end

  def photo_tags
    tags = Array.new
    self.photos.each{ |photo|
      tags = tags | photo.tags
    }
    return tags
   end

  protected

  private
  
  def create_folders
    #Dir.mkdir( APP_CONFIG[:photos_path] + self.path ) unless File.exists?( APP_CONFIG[:photos_path] + self.path )
    #Dir.mkdir( APP_CONFIG[:thumbs_path] + self.path ) unless File.exists?( APP_CONFIG[:thumbs_path] + self.path )
  end
  
  def destroy_folders
    #puts "DELETE DIRECTORY " + APP_CONFIG[:photos_path] + self.path
    #Dir.delete( APP_CONFIG[:photos_path] + self.path ) if File.exists?( APP_CONFIG[:photos_path] + self.path )
    #Dir.delete( APP_CONFIG[:thumbs_path] + self.path  ) if File.exists?( APP_CONFIG[:thumbs_path] + self.path )
  end
end

app/controllers/albums_controller.rb
# encoding: UTF-8

class AlbumsController < ApplicationController
  before_filter :check_public_access
  before_filter :require_role_admin, :only => [:untouched, :new, :create, :edit, :update, :destroy]
  
  def index
    if params[:tag_id]
      @albums = Album.find(:all, :conditions => [ "id IN ( SELECT DISTINCT photos.album_id FROM photos WHERE photos.id IN ( SELECT photo_id FROM photo_tags WHERE photo_tags.tag_id = :q) )", { :q => Tag.find( params[:tag_id] ).id } ], :order => 'title')
    elsif params[:q]
      #search = params[:q]
      #search = search.split("AND").map{|q|q.strip}
      #@albums = Album.find(:all, :select => 'DISTINCT albums.id, albums.title', :limit => 20, :conditions => {  :tags => {:title => search}}, :joins => 'LEFT OUTER JOIN photos ON albums.id = photos.album_id LEFT OUTER JOIN photo_tags ON photos.id = photo_tags.photo_id LEFT OUTER JOIN tags ON photo_tags.tag_id = tags.id', :order => "albums.title ASC" )
      #@albums = Album.find(:all, :select => 'DISTINCT album_id', :conditions => [ "title LIKE :q OR description LIKE :q OR id IN ( SELECT DISTINCT photos.album_id FROM photos WHERE photos.description LIKE :q OR photos.title LIKE :q OR photos.id IN ( SELECT photo_id FROM photo_tags LEFT OUTER JOIN tags ON photo_tags.tag_id = tags.id WHERE tags.title LIKE :q) )", { :q => '%' + params[:q] + '%' } ], :order => 'title')
      params[:q].split(" AND ").each {|q|
        qphotos = Photo.find(:all, :select => 'DISTINCT album_id', :conditions => [ "description LIKE :q OR title LIKE :q OR id IN ( SELECT photo_id FROM photo_tags LEFT OUTER JOIN tags ON photo_tags.tag_id = tags.id WHERE tags.title LIKE :q)", { :q => '%' + q + '%' } ])
        qalbums = Album.find(:all, :conditions => ['title LIKE :q OR description LIKE :q OR id IN (:ids)', { :ids => qphotos.map{|p|p.album_id}, :q => '%' + q + '%'  }], :order => 'title' )
        if @albums
          @albums = @albums & qalbums
        else
          @albums = qalbums
        end
      }

    else
      @albums = Album.find(:all, :order => 'title')
    end
    respond_to do |format|
      format.html
      format.json  { render :json => @albums }
      format.xml  { render :xml => @albums }
    end
  end

  def untouched
    @albums = Album.untouched()
    respond_to do |format|
      format.html
      format.json  { render :json => @albums }
      format.xml  { render :xml => @albums }
    end
  end
  
  def show
    @album = Album.find( params[:id])
    respond_to do |format|
      format.html
      format.json  { render :json => @album }
      format.xml  { render :xml => @album }
      format.pdf { render :pdf => @album.title }
    end
  end

  def new
    @album = Album.new
  end

  def create
    @album = Album.new(params[:album])

    if @album.save
      flash[:notice] = "Album erstellt! Füge jetzt gute Fotos hinzu"
      if params[:collection_id]
        @album.collections << Collection.find( params[:collection_id] )
        redirect_to upload_collection_album_photos_path(params[:collection_id], @album )
      else
        redirect_to upload_album_photos_path( @album )
      end
    else
      render :action => :new
    end
  end

  def edit
    @album = Album.find( params[:id])
  end

  def update
    @album = Album.find( params[:id])
    if @album.update_attributes(params[:album])
      flash[:notice] = "Album bearbeitet"
      if params[:collection_id]
        redirect_to collection_album_path(params[:collection_id], @album )
      else
        redirect_to @album
      end
    else
      render :action => :edit
    end
  end
  
  def destroy
    @album = Album.find( params[:id])
    if @album.destroy
      if params[:collection_id]
        redirect_to collection_path(params[:collection_id] )
      else
        redirect_to albums_path
      end
    else
      redirect_to @album
    end
  end
  
end

app/helpers/albums_helper.rb
module AlbumsHelper
  def new_upload_path_with_session_information
      session_key = self.get_session_key
      photos_path(session_key => cookies[session_key], request_forgery_protection_token => form_authenticity_token)
  end

  def get_session_key
    Rails.application.config.session_options[:key]
  end
end

app/views/albums/_album.html.erb
<p><%= render :partial => "photos/thumb", :locals => { :photo => album.photos.find(:first), :photosize => 'collection' } unless album.photos.empty? %></p>

app/views/albums/_form.html.erb
<%= content_for :javascript do %>
<%= javascript_include_tag "http://maps.google.com/maps/api/js?sensor=true" -%>
<%= javascript_include_tag "tag/tag"  -%>
<% end %>

<div id="map_canvas"></div>

<%= hidden_field_tag :all_tags, "'#{Tag.find(:all).map { |tag| tag.title }.join('\',\'')}'" %>
<%= hidden_field_tag :collection_id, params[:collection_id] %>
<%= form.hidden_field :id %>
<%= form.hidden_field :latitude %>
<%= form.hidden_field :longitude %>

<%= form.label :title, {:class => 'big'} %><br />
<%= form.text_field :title, {:class => 'big'} %><br />

<%= form.label :description %><br />
<%= form.text_area :description %><br />

<%= form.label :address %><br />
<%= form.text_area :address, { :rows => 3} %><br />

<%= form.label :note %><br />
<%= form.text_area :note %><br />

<%= form.label :tags %><br />
<%= form.text_field :tags, { :autocomplete => "off", :class => 'tag_list', :value => (@album.tags.map{|tag|tag.title}.join(" ") unless @album.tags.nil?) } %><br />

<br />
Beinhaltet: <%= @album.photos.count %> Fotos<br/>

app/views/albums/edit.html.erb
<h1>Album Bearbeiten</h1>
 
<%= form_for @album do |f| %>
  <%= f.error_messages %>
  <%= render :partial => "form", :object => f %>
  <%= f.submit "Speichern" %>
<% end %>
 
<%= content_for :action_links do %>
<% if has_role?("admin") %>

<%= link_to("Album Löschen", { :action => "destroy", :id => @album, :collection_id => params[:collection_id] },
  :confirm => "Bist du sicher das du dieses Album löschen möchtest?",
  :method => :delete) %>
<% end %>
<% end %>

app/views/albums/index.html.erb
<% for album in @albums %>
<div class="row">
  <div class="title">
	<%= render :partial => "photos/thumb", :locals => {:photo => album.photos.first } unless album.photos.empty? %>
	<p><%= link_to album.title, album %></p>
  </div>
  <div class="image">
	<%= render :partial => "photos/thumb", :collection => album.photos.find(:all, :limit => 5, :offset => 1), :as => :photo %>
  </div>
</div>
<% end %>

<%= content_for :action_links do %>
<%= link_to "Zeig mir nur die Photos die mit #{params[:q]} getagt sind", photos_path(:q => params[:q]) if params[:q] %>
<% if has_role?("admin") %>
<%= " |&nbsp;" if params[:q] %>
<%= link_to "Neues Album", new_album_path() %>
<% end %>
<% end %>

app/views/albums/new.html.erb
<h1>Neues Album</h1>
 
<%= form_for @album do |f| %>
  <%= f.error_messages %>
  <%= render :partial => "form", :object => f %>
  <%= f.submit "Anlegen" %>
<% end %>
 

app/views/albums/show.html.erb
<h2><%= @album.title %></h2>

<%= content_for :javascript do %>
<%= javascript_include_tag "http://maps.google.com/maps/api/js?sensor=true" -%>
<% end %>

<div id="multipleimages">
<table>
	<% count = 0.0 %>
	<% for photo in @album.photos.find(:all, :order => "Id ASC") %>
	<% count += 1%>
  	<% if count == 1 || ( (count-1) / 4.0 == ( (count-1) / 4.0).to_i ) %><tr><% end %>
	<td><%= link_to image_tag( photo.file.preview.url ), [@album.collections.first, @album, photo] %></td>
  	<% if count / 4.0 == (count / 4.0).to_i %></tr><% end %>
	<% end %>
</table>
</div>

<p><%= @album.description %></p>

<% unless @album.photo_tags.empty? %>
<p>Getaggt mit: 
<% for tag in @album.photo_tags.map{|tag|tag.title}.sort %>
<%= link_to tag, album_tag_photos_path(@album, tag) %>
<% end %>
</p>
<% end %>

<% unless @album.collections.empty? %>
<p>Gehört zu: 
<% for collection in @album.collections.find(:all, :order => 'title') %>
<%= link_to collection.title, collection_path(collection) %>
<% end %>
</p>
<% end %>

<% if has_role?("admin") %>
<p><%= @album.address %></p>
<% end %>
<% if has_role?("admin") %>
<p><%= @album.note %></p>
<% end %>

<a href='#' id='map' data-address='<%= @album.address %>'>Karte</a>
<div id="big_map_canvas"></div>

<%= content_for :action_links do %>
<% if has_role?("admin") %>
<% if params[:collection_id] %>
<%= link_to "PDF", collection_album_path(params[:collection_id],@album, :format => 'pdf') %> |&nbsp;
<%= link_to "Album bearbeiten", edit_collection_album_path(params[:collection_id],@album) %> |&nbsp;
<%= link_to "Alle Fotos Bearbeiten", edit_multiple_collection_album_photos_path(params[:collection_id],@album) %> |&nbsp;
<%= link_to "Unfertige Fotos Bearbeiten", untouched_collection_album_photos_path(params[:collection_id], @album) %> |&nbsp;
<%= link_to "Foto hinzufügen", upload_collection_album_photos_path(params[:collection_id], @album) %>
<% else %>
<%= link_to "PDF", album_path(@album, :format => 'pdf') %> |&nbsp;
<%= link_to "Album bearbeiten", edit_album_path(@album) %> |&nbsp;
<%= link_to "Alle Fotos Bearbeiten", edit_multiple_album_photos_path(@album) %> |&nbsp;
<%= link_to "Unfertige Fotos Bearbeiten", untouched_album_photos_path(@album) %> |&nbsp;
<%= link_to "Foto hinzufügen", upload_album_photos_path(@album) %>
<% end %>

<% end %>
<% end %>

app/views/albums/show.pdf.erb
<h1><%= @album.title %></h1>

<%= render :partial => @album.photos %>

app/views/albums/untouched.html.erb
<% for album in @albums %>
<div class="row">
  <div class="title">
	<%= render :partial => "photos/thumb", :locals => {:photo => album.photos.first } unless album.photos.empty? %>
	<p><%= link_to album.title, album %></p>
  </div>
  <div class="image">
	<%= render :partial => "photos/thumb", :collection => album.photos.find(:all, :limit => 5, :offset => 1), :as => :photo %>
  </div>
</div>
<% end %>