config/routes.rb
Balder::Application.routes.draw do
  resource :account, :controller => :users
  match "login", :to => "user_sessions#new", :as => :login
  match "authenticate", :to => "user_sessions#create", :as => :authenticate
  match "logout", :to => "user_sessions#destroy", :as => :logout

  resources :photos do
    collection do
      get :untouched
      post :edit_multiple
      put :update_multiple
      get :upload
      get :scan
    end
  end
  resources :albums do
    collection do
      get :untouched
    end
    resources :tags do
      resources :photos do
        collection do
          get :untouched
          get :upload
          get :edit_multiple
        end
      end
    end
    resources :photos do
      collection do
        get :untouched
        get :upload
        get :edit_multiple
      end
    end
  end
  resources :collections do
    resources :albums do
      resources :photos do
        collection do
          get :untouched
          get :upload
          get :edit_multiple
        end
      end
    end
  end
  
  resources :tags, :shallow => true do
    resources :photos
    resources :albums
  end
  
  resources :users, :controller => "admin/users"
  
  root :to => "collections#index"

end

app/models/photo.rb
class Photo < ActiveRecord::Base
  # TODO: path not used? it should be removed from the DB

  belongs_to :album
  has_many :photo_tags, :dependent => :destroy
  has_many :tags, :through => :photo_tags
  
  mount_uploader :file, FileUploader
  
  validates :title, :presence => true
  
  before_validation :set_title
  # before_create :exif_read
  # before_update :exif_write

  attr_accessor :tag_list
  
  scope :untouched, :conditions => "photos.description IS NULL AND photos.id NOT IN ( SELECT photo_id FROM photo_tags)", :include => :album 
  scope :previous, lambda { |p,a| { :conditions => ["id < :id AND album_Id = :album ", { :id => p, :album => a } ], :limit => 1, :order => "id DESC"} }
  scope :next, lambda { |p,a| { :conditions => ["id > :id AND album_Id = :album ", { :id => p, :album => a } ], :limit => 1, :order => "id ASC"} }

  def to_param
    "#{id}-#{title.parameterize}"
  end
  
  def tag(title)
    return if self.tags.collect{|tag|tag.title}.include?( title )
    self.photo_tags.create(:tag => Tag.find_or_create_by_title( :title => title) )
    self.reload
  end
  
  def untag(title)
    return if !self.tags.collect{|tag|tag.title}.include?( title )
    # perhaps not the best way but it finds the correct PhotoTag and deletes it
    self.photo_tags.select{|photo_tag|
      photo_tag.tag.title == title
    }.each {|photo_tag|photo_tag.destroy}
    self.reload
  end

  def tag_list
    return self.tags.find(:all, :order => 'title').map{ |t| t.title }.sort.join(" ")
  end

  def tag_list=(tags)
    ts = Array.new
    tags.split(" ").each do |tag|
      ts.push( Tag.find_or_create_by_title( :title => tag.downcase) )
    end
    self.tags = ts
  end

  def _delete
    0
  end
  

  private

  def set_title
    self.title = self.file.file.basename.titleize unless self.title
  end

  def exif_read
    photo = MiniExiftool.new(self.file.file.file)
    self.longitude = photo.GPSLongitude if self.longitude.nil?
    self.latitude = photo.GPSLatitude if self.latitude.nil?
    self.title = photo.DocumentName if self.title.nil?
    self.description = photo.ImageDescription if self.description.nil? && photo.ImageDescription != 'Exif_JPEG_PICTURE'
    self.tag_list = (self.tags.empty? ? "" : self.album.tag_list) + " " + (photo.Keywords.nil? ? "" : photo.Keywords.to_a.map { |tag| tag.gsub(" ", "_") }.join(" "))
  end
  
  def exif_write
    # should only write if tags are changed as images can be large and thus ExifTool will take a while to write to the file
    photo = MiniExiftool.new(self.file.file.file)
    photo.GPSLongitude = self.longitude
    photo.GPSLatitude = self.latitude
    photo.DocumentName = self.title
    photo.ImageDescription = self.description
    photo.Keywords = self.tags
    photo.save
  end

end

app/controllers/photos_controller.rb
# encoding: UTF-8

class PhotosController < ApplicationController
  before_filter :check_public_access
  before_filter :require_role_admin, :only => [:untouched, :upload, :new, :create, :edit, :update, :destroy, :scan]

  def index
    if params[:tag_id] && params[:album_id]
      @tag = Tag.find_by_title!( params[:tag_id] )
      @photos = @tag.photos.find(:all, :conditions => ['photos.album_id = :album', {:album => Album.find(params[:album_id] ) } ], :order => "photos.id ASC")
    elsif params[:tag_id]
      @tag = Tag.find_by_title!( params[:tag_id] )
      @photos = @tag.photos.find(:all, :order => "photos.id ASC")
    elsif params[:album_id]
      @album = Album.find( params[:album_id])
      @photos = @album.photos.find(:all, :order => "photos.id ASC")
    elsif params[:q]
      #search = params[:q]
      #search = search.split("AND").map{|q|q.strip}
      #@photos = Photo.find(:all, :select => 'DISTINCT photos.id, photos.album_id, photos.title, photos.path', :limit => 20, :conditions => {  :tags => {:title => search}}, :joins => 'LEFT OUTER JOIN photo_tags ON photos.id = photo_tags.photo_id LEFT OUTER JOIN tags ON photo_tags.tag_id = tags.id', :include => [:album], :order => "photos.title ASC" )
      params[:q].split(" AND ").each {|q|
        qphotos = Photo.find(:all, :limit => 20, :conditions => [ "photos.description LIKE :q OR photos.title LIKE :q OR photos.id IN ( SELECT photo_id FROM photo_tags LEFT OUTER JOIN tags ON photo_tags.tag_id = tags.id WHERE tags.title = :t) ", { :q => '%' + q + '%', :t => q } ], :include => :album, :order => "photos.id ASC" )
        if @photos
          @photos = @photos & qphotos
        else
          @photos = qphotos
        end
      }
    else
      @photos = Photo.find(:all, :order => "photos.id ASC")
    end
    respond_to do |format|
      format.html
      format.json  { render :json => @photos }
      format.xml  { render :xml => @photos }
    end
  end
  
  def untouched
    if params[:album_id]
      @album = Album.find( params[:album_id])
      @photos = @album.photos.untouched
    else
      @photos = Photo.untouched()
    end
    respond_to do |format|
      format.html
      format.json  { render :json => @photos }
      format.xml  { render :xml => @photos }
    end
  end
  
  def show
    @photo = Photo.find( params[:id] )
    previous_rs = Photo.previous( @photo.id, @photo.album )
    @previous = previous_rs.first unless previous_rs.empty?
    next_rs = Photo.next( @photo.id, @photo.album )
    @next = next_rs.first unless next_rs.empty?
    respond_to do |format|
      format.html
      format.json  { render :json => @photo }
      format.xml  { render :xml => @photo }
    end
  end
  
  def scan
  	require "scan"
  	ScanFiles.Scan(false)
  	redirect_to(root_path)
  end

  def new
    @photo = Photo.new
  end

  def upload
    @album = Album.find( params[:album_id])
  end

  def create
    @photo = Photo.new(params[:photo])
    @photo.file = params[:file]
    respond_to do |format|
        if @photo.save
          format.html { render :text => "FILEID:" + @photo.file.album.url }
          format.xml  { render :nothing => true }
        else
          format.html { render :text => "ERRORS:" + @photo.errors.full_messages.join(" "), :status => 500 }
          format.xml  { render :xml => @photo.errors, :status => 500 }
        end
    end
  end
  
  def edit
    @photo = Photo.find( params[:id])
    @tags = Tag.find(:all).map { |tag| tag.title }.join('\',\'')
  end
  
  def edit_multiple
    if params[:album_id]
      @album = Album.find( params[:album_id] )
      @photos = @album.photos
    else
      @photos = Photo.find( params[:photo_ids] )
    end
  end

  def update
    @photo = Photo.find( params[:id])
    if @photo.update_attributes(params[:photo])
      flash[:notice] = "Photo bearbeitet"
      if params[:collection_id]
        redirect_to collection_album_photo_path( params[:collection_id], params[:album_id], @photo )
      elsif params[:album_id]
        redirect_to album_photo_path( params[:album_id], @photo )
      else
        redirect_to @photo
      end
    else
      render :action => :edit
    end
  end

  def update_multiple
    @photos = params[:photos][:photo]
    @photos.each do |photo_item|
      photo = Photo.find( photo_item[0] )
      if photo_item[1][:_delete] == "1"
        photo.destroy
      else
        photo.title = photo_item[1][:title]
        photo.tag_list = photo_item[1][:tags]
        photo.save
      end
    end
    flash[:notice] = "Fotos bearbeitet"
    redirect_to photos_path
  end
  
  def destroy
    @photo = Photo.find( params[:id])
    @album = @photo.album
    if @photo.destroy
      if params[:collection_id]
        redirect_to collection_album_path( params[:collection_id], @album )
      else
        redirect_to @album
      end
    else
      redirect_to @photo
    end
  end
end

app/views/photos/_form.html.erb
<%= content_for :javascript do %>
<%= javascript_include_tag "tag/tag"  -%>
<% end %>
<%= hidden_field_tag :all_tags, @tags %>
<%= form.label :title %><br />
<%= form.text_field :title %><br />
<br />
<%= form.label :tag_list %><br />
<%= form.text_field :tag_list, { :autocomplete => "off", :class => 'tag_list'} %><br />
<br />
<%= form.label :description %><br />
<%= form.text_area :description %><br />
<br/>
<p>On disk: ~/<%= @photo.file.path %></p>

app/views/photos/_photo.pdf.erb
<%= image_tag photo.file.single.url %><br/>

app/views/photos/_thumb.html.erb
<%= link_to (image_tag eval('photo.file.' + (defined?(photosize) ? photosize : "album") + '.url') ), [photo.album.collections.first, photo.album, photo] %>

app/views/photos/edit.html.erb
<h1>Foto bearbeiten</h1>

<%= image_tag @photo.file.preview.url %>
 
<%= form_for @photo do |f| %>
<%= hidden_field_tag :collection_id, params[:collection_id] %>
<%= hidden_field_tag :album_id, params[:album_id] %>
  <%= f.error_messages %>
  <%= render :partial => "form", :object => f %>
  <%= f.submit "Update" %>
<% end %>

<%= content_for :action_links do %>
<%= link_to("Foto löschen", { :action => "destroy", :id => @photo, :collection_id => params[:collection_id] },
  :confirm => "Bist du sicher das du dieses Foto löschen möchtest?",
  :method => :delete) %>
<% end %>

app/views/photos/edit_multiple.html.erb
<%= form_for :photos, :url => update_multiple_photos_path, :html => { :method => :put } do |f| %>
<% for photo in @photos %>
<p>
<%= f.fields_for photo, :index => photo.id do |p|%>
	<%= p.check_box :_delete  %>
	<%= render :partial => "photos/thumb", :locals => {:photo => photo } %>
	<%= p.text_field :title %>
	<%= p.text_field :tags, :value => photo.tag_list %>
<% end%>
</p>
<% end%>
  <p><%= f.submit "Speichern" %></p>
<% end %>

<br /><%= link_to "Zurück zum Album '#{@album.title}'", @album %>

app/views/photos/index.html.erb
<ul><%= render :partial => 'photos/thumb',:collection => @photos, :as => :photo %></ul>

<%= content_for :action_links do %>
<%= link_to "Zeige Alben die Fotos mit folgenen Tags besitzen: #{params[:q]}", albums_path(:q => params[:q]) if params[:q] %>
<%= link_to "Zeige alle Fotos die folgende Tags besitzen: #{params[:tag_id]}", tag_photos_path(params[:tag_id]) if params[:tag_id] && params[:album_id] %>
<% end %>

app/views/photos/show.html.erb
<h2><%= @photo.title%></h2>

<div id="fullimage">
	<div id="navigation">
		<p class="links">
			<% unless @previous.nil? %>
			<%= link_to "Zurück", [ @photo.album.collections.first, @photo.album, @previous] %>
			<% unless @next.nil? %>
			 | 
			<% end %>
			<% end %>
			<% unless @next.nil? %>
			<%= link_to "Weiter", [ @photo.album.collections.first, @photo.album, @next] %> 
			<% end %>
		</p>
	</div>
  <p><%= link_to_if @next, image_tag(@photo.file.single.url ), [ @photo.album.collections.first, @photo.album, @next] %></p>
</div>

<p><%= @photo.description %></p>
<p>Getaggt mit:
<% for tag in @photo.tags.map{|tag|tag.title}.sort %>
<%= link_to tag, tag_photos_path(tag) %>
<% end %>

<%= content_for :action_links do %>
<% if has_role?("admin") %>
<% if params[:collection_id] %>
<%= link_to "Foto bearbeiten", edit_collection_album_photo_path(params[:collection_id], params[:album_id], @photo) %>
<% else %>
<%= link_to "Foto bearbeiten", edit_photo_path(@photo) %>
<% end %>
<% end %>
<% end %>

app/views/photos/untouched.html.erb
<%= form_for :photos, :url => update_multiple_photos_path, :html => { :method => :put } do |f| %>
<% for photo in @photos %>
Bitte gib Titel und Tags an
<p>
<%= f.fields_for photo do |p|%>
	<%= render :partial => "photos/thumb", :locals => {:photo => photo } %>
	<%= p.text_field :title, :index => photo.id %>
	<%= p.text_field :tags, :index => photo.id, :value => photo.tag_list %>
<% end%>
</p>
<% end%>
  <p><%= f.submit "Speichern" %></p>
<% end %>

app/views/photos/upload.html.erb
<%= content_for :javascript do %>
<style type="text/css">@import url(/javascripts/plupload/js/jquery.plupload.queue/css/jquery.plupload.queue.css);</style>
<%= javascript_include_tag "plupload/js/plupload.full.js" -%>
<%= javascript_include_tag "plupload/js/jquery.plupload.queue/jquery.plupload.queue.js"  -%>

<script type="text/javascript">
$(document).ready(function() {
	
	$("#uploader").pluploadQueue({
			// General settings
			runtimes : 'flash,html5,browserplus,silverlight,gears',
			url : '<%= photos_path %>',
			max_file_size : '10mb',
			multipart: true,  
			   multipart_params: {  
				'<%= get_session_key %>' : encodeURIComponent('<%= cookies[get_session_key] %>'),
				'authenticity_token' : '<%= form_authenticity_token %>',
				'photo[album_id]' : "<%= @album.id %>"
			   },

			// Resize images on clientside if we can
			//resize : {width : 320, height : 240, quality : 90},

			// Specify what files to browse for
			filters : [
				{title : "Image files", extensions : "jpg,gif,png,bmp,jpeg,tif,tiff"}
			],

			// Flash settings
			flash_swf_url : '/javascripts/plupload/js/plupload.flash.swf',

			// Silverlight settings
			silverlight_xap_url : '/javascripts/plupload/js/plupload.silverlight.xap',
			
			// Post init events, bound after the internal events
				init : {

					FileUploaded: function(up, file, info) {
						// Called when a file has finished uploading
						res = info.response;
						if (res.substring(0, 7) === "FILEID:") {
							var image = $('<img>').appendTo('#thumbs')
							image.css('display','none')
							image.attr('src', res.substring(7) )
							image.fadeIn('slow')
						}
					}
				}
		});

		// Client side form validation
		$('form').submit(function(e) {
			var uploader = $('#uploader').pluploadQueue();

			// Validate number of uploaded files
			if (uploader.total.uploaded == 0) {
				// Files in queue upload them first
				if (uploader.files.length > 0) {
					// When all files are uploaded submit form
					uploader.bind('UploadProgress', function() {
						if (uploader.total.uploaded == uploader.files.length)
							$('form').submit();
					});

					uploader.start();
				} else
					alert('You must at least upload one file.');

				e.preventDefault();
			}
		});
})
</script>
<% end %>

<form>
<div id="uploader">
        <p>You browser doesn't have Flash, Silverlight, Gears, BrowserPlus or HTML5 support.</p>
    </div>

<br>
<div id="thumbs"></div>
</form>

<br><%= link_to "Hochgeladene Fotos bearbeiten", untouched_album_photos_path( @album ) %>
<br><%= link_to "Zurück zum Album '#{@album.title}'", @album %>